services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "5080:80"
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: facturacion_buffet
      DB_USERNAME: root
      DB_PASSWORD: aldana1234

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: aldana1234
      MYSQL_DATABASE: facturacion_buffet
    expose:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
