version: '3.3'

services:
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    ports:
      - "5080:80"
    working_dir: /var/www/html
    volumes:
        - .:/var/www/html
        - storage-volume:/var/www/html/storage
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: facturacion_buffet
      DB_USERNAME: root
      DB_PASSWORD: aldana1234

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: aldana1234
      MYSQL_DATABASE: facturacion_buffet
    volumes:
      - ./db:/var/lib/mysql

volumes:
  storage-volume:
